### ISSUE TITLE
Database connection drops continuously (0.9.3)

### ISSUE THREAD

**Issue by cianiandreadev** [bitmagnet-io/bitmagnet#287] opened 2024-06-27 10:27 UTC
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

After migrating to 0.9.3 I noticed very high cpu load on postgres.
Checking the logs I noticed the connection between postgres and bitmagnet continuously drops and restart.

I tried to reboot multiple times but did not help.

Migrations are completed according to Bitmagnet log.

### Environment Information (Required)

- Bitmagnet version: `[0.9.3]`
- OS and version: `[Docker]`

### Additional context

These are the logs:
```
2024-06-27 10:23:33.115 UTC [8656] ERROR:  canceling statement due to user request
2024-06-27 10:23:33.115 UTC [8656] STATEMENT:  SELECT EXISTS(SELECT * FROM "content" WHERE "content"."type" = 'movie' AND ("content"."release_date" >= '2015-01-01 00:00:00' AND "content"."release_date" < '2016-01-01 00:00:00') AND content.tsv @@ '800 <-> words'::tsquery)
2024-06-27 10:23:33.116 UTC [8656] LOG:  could not send data to client: Connection reset by peer
2024-06-27 10:23:33.116 UTC [8656] FATAL:  connection to client lost
2024-06-27 10:23:33.136 UTC [8677] ERROR:  canceling statement due to user request
```

I noticed that the Statement change, but the error is repeated at every different statement.

**Comment by mgdigital** [comment] 2024-06-27 10:32
> After migrating to 0.9.3 I noticed very high cpu load on postgres.

Hi, please see the release note for 0.9.0 and the re-index required for ordering. The queue needs to work through all existing torrents to add missing fields. This did cause performance issues for some users which are mitigated by reducing the queue concurrency. Letting the queue work down will allow load to return to normal (or clearing it altogether, but then your ordering won't fully work). Can I ask about your hardware setup and specifically the disk that the DB is running on? It's recommended to run the database on a fast SSD.

**Comment by cianiandreadev** [comment] 2024-06-27 11:47
Hi @mgdigital , 
Thanks for the support

The machine has the following specs (no docker restrictions are applied)

CPU: Intel i5-6400 @ 2.7GHz
RAM: 64GB
SSD: Crucial_CT480M500SSD1 

This issue is running since ~ 16h

Number of entries in bitmagnet (taken by opening the webinterface and read the ALL count) `All ~14,527,984`

**Comment by cianiandreadev** [comment] 2024-06-27 11:52
If this can help, here you can find the Grafana charts for Bitmagnet.
We can clearly see the spike of CPU usage (and Disk I/O indeed) after the update.

What still is not clear (even if the db is re-indexing) is WHY the connection drop error in the logs.

<img width="1240" alt="Screenshot 2024-06-27 at 13 50 24" src="https://github.com/bitmagnet-io/bitmagnet/assets/1215511/8c259d82-0c38-4237-b66c-37f7f2cfc8e0">

**Comment by mgdigital** [comment] 2024-06-27 11:57
Hi, do you have any failed jobs (in your `queue_jobs` table), and if so what are the error messages? Note if you see any "missing <n> info hashes" these are to be expected and will be silenced in a future release. If you don't see any errors aside from that then as far as Bitmagnet is concerned "everything is fine". While there have been a few teething issues with this queue job, they seem to be resolved for most users and this is the first I've heard of anyone having dropped connections - you may have some mileage in tweaking your Postgres config, increasing the memory available to it etc...

**Comment by mgdigital** [comment] 2024-06-27 12:23
This should do it:

```
SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
```

**Comment by mgdigital** [comment] 2024-06-27 12:24
> I will try to leave the container running for another day

If you have 15 million torrents this would take (in normal conditions) a couple of days for the full reindex queue to work down, but much longer if you're experiencing I/O issues.

**Comment by DerBunteBall** [comment] 2024-06-27 12:24
Die you change the docker-compose file?

Set the PosgreSQL shm_size to 2GB für the start. Normally this houldn't lead to some RAM consume.

I have in a peak (with imports) shitty I/O and poorer CPU max 2,8GB total memory usage on the system.

**Comment by cianiandreadev** [comment] 2024-06-27 12:26
> This should do it:
> 
> ```
> SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
> ```

Thank you very much:

The output seems optimistic:

```
bitmagnet=# SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
 error 
-------
(0 rows)
```

**Comment by cianiandreadev** [comment] 2024-06-27 12:28
> Die you change the docker-compose file?
> 
> Set the PosgreSQL shm_size to 2GB für the start. Normally this houldn't lead to some RAM consume.
> 
> I have in a peak (with imports) shitty I/O and poorer CPU max 2,8GB total memory usage on the system.

Hi @DerBunteBall , 
The docker-compose file has the following:

```yml
  postgres:
    image: postgres:16.0-alpine
    container_name: bitmagnet-postgres
    volumes:
      - ${ROOT}/data/postgres:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432" Expose this port if you'd like to dig around in the database
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=******
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
```

**Comment by DerBunteBall** [comment] 2024-06-27 12:32
I guess that's because the SQL dies in general.... So nothing gets into the DB. So it's not the failed jobs instead the completely crazy PostgreSQL. Or the fact we can't see it correctly. But normally the Bitmagnet container prints the errors also.

Increase the shm_size a bit. Let's say 2GB bring down the project and restart it.

And eventually try this:

```yml
command:
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "synchronous_commit=off"
```

Some nice guy on the Discord posted that a few days ago. I have added these options and after a week of operation it seems they also help since 0.9.x there are also tuning infos on the web. But I haven't looked deeper into that.

**Comment by DerBunteBall** [comment] 2024-06-27 12:34
You can increase the shared_buffers up to 512MB with 2GB. The documentation for the option sys 1/4 of the memory the DB has available should be ok.

And as hint: Some older mainboards still had SATA-2 connectors. They were not always well marked. If in doubt check that the SSD is really attached to a SATA-3 connector.

**Comment by mgdigital** [comment] 2024-06-27 12:35
Do you have any succeeded jobs? Visit the `/metrics` endpoint and check:

```
bitmagnet_queue_jobs_total{queue="process_torrent",status="processed"} 
```

If you see a positive number here, and nothing for:

```
bitmagnet_queue_jobs_total{queue="process_torrent",status="failed"} 
```
 
(which you already confirmed), then officially "everything is fine". You can monitor the metrics endpoint for the queue throughput, if you're seeing the number increase by (say) 10 or so per minute then that's what I'd expect if everything is working normally.

**Comment by cianiandreadev** [comment] 2024-06-27 12:38
@mgdigital 

![Screenshot 2024-06-27 at 14 37 23](https://github.com/bitmagnet-io/bitmagnet/assets/1215511/0894fdb1-58e5-4ac3-9bd5-d5abf75fba3f)

That is all about `bitmagnet_queue_jobs_total`. No more matches in the search.

I will also try to increase the `shm_size` to 2GB as @DerBunteBall proposed.

**Comment by mgdigital** [comment] 2024-06-27 12:40
This looks very normal to me in this case...

**Comment by DerBunteBall** [comment] 2024-06-27 12:40
And play around a bit with concurrency. 0.9.2 or 3 should start with 1 you should be always fine with 2. I guess with SSD 3. But expect a nice CPU load in some situationes (I guess 4-6 within import/reprocess/index) so an i5 6400 is relatively compareable to the i3 I use.

You are in big process. High CPU is normal. I guess your SQL needs a bit twaking. Increase the shm_size and add the command section.

Then check again. I guess it will be better. 0.9.x should be at a concurrency of 1. You should be fine with 2 with that setup.

**Comment by cianiandreadev** [comment] 2024-06-27 12:42
Ok. 
Increased the `shm_size` to 2g.
I'll implement the commands proposed by @DerBunteBall  and leave this running by checking this values time to time.
I'll write down a reminder to update this issue in a couple of days.
Thanks you both for now for the support!

**Comment by mgdigital** [comment] 2024-06-27 12:44
Closing this for now. Consider joining the Discord if you're having any further issues: https://discord.gg/6mFNszX8qM

**Closed by mgdigital** 2024-06-27 12:44 UTC
Labels: bug

**Comment by cianiandreadev** [comment] 2024-07-01 11:30
Hi @mgdigital ,

As promised I came back to update.
Seems indeed that the high cpu usage from postgres is now mitigated, after around 5 days.

What is a bit still strange is that the errors are still present in the logs:

```
2024-07-01 11:28:05.033 UTC [1] LOG:  database system is ready to accept connections
2024-07-01 11:28:07.118 UTC [41] ERROR:  canceling statement due to user request
2024-07-01 11:28:07.118 UTC [41] STATEMENT:  SELECT * FROM "content_attributes" WHERE ("content_attributes"."content_type","content_attributes"."content_source","content_attributes"."content_id") IN (($1,$2,$3))
2024-07-01 11:28:07.118 UTC [41] LOG:  could not send data to client: Broken pipe
2024-07-01 11:28:07.118 UTC [41] FATAL:  connection to client lost
```

**Comment by kureta** [comment] 2024-10-24 20:56
I think `"synchronous_commit=off"` should be a default flag. db server performs much more reliably this way. before, it was becoming unresponsive from time to time (unhealthy).
