### ISSUE TITLE
0.9.4 doesn't process jobs

### ISSUE THREAD

**Issue by DerBunteBall** [bitmagnet-io/bitmagnet#293] opened 2024-07-04 14:04 UTC
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

0.9.4 doesn't process jobs.

The job queue gets filled with new jobs and cleanup happens but no processing of pending jobs. Waited around 50 minutes.

Checking /metrics proccessed and failed jobs go down (cleanup after 24 hrs) and pending jobs just grow.

That this is not just a wrong output is also indicated by system load. It's very low.

### To Reproduce

Bring up 0.9.4 and look what's going on at /metrics.

### Expected behavior

Normal job processing. Eventually with a bit lower system load then with 0.9.3.

### Environment Information (Required)

- Bitmagnet version: `0.9.4`
- OS and version: `Debian`
- Please specify any config values for which you have overridden the defaults: `dht_crawler.save_pieces=true,dht_crawler.concurrency=x,dht_crawler.save_files_threshold=x,tmdb.enabled=false`

### Additional context

None

**Comment by mgdigital** [comment] 2024-07-04 14:13
Hi, I'm not convinced that no jobs are running, since they get archived after 24 hours the processed count can go down while everything's working fine.

What does this query give you?

```sql
select ran_at from queue_jobs where status = 'processed' order by ran_at desc limit 1;
```

If it gives you a recent time then everything is fine...

**Comment by DerBunteBall** [comment] 2024-07-04 14:16
2024-07-04 14:31:10.633 +0200

Nearly two hours old. Updated shortly after release and it runs since that moment.

**Comment by mgdigital** [comment] 2024-07-04 14:18
> 2024-07-04 14:31:10.633 +0200
> 
> Nearly two hours old. Updated shortly after release and it runs since that moment.

Does the queue worker log any errors? Can you make sure it's definitely running? (maybe try running it in isolation)

**Comment by DerBunteBall** [comment] 2024-07-04 14:46
Hm.....

Not an error. The debug log log file show gorm messages which are shown when jobs are processed.

It's running in Docker. Restarted with disabled DHT Crawler and WebUI. But the query alsways gives the same result.

System load is at 1.3-1.8 with 0.9.3 in normal operation it was around 6.5-7.8.

Hm.....

**Comment by mgdigital** [comment] 2024-07-04 15:33
As I mentioned on Discord, this is almost certainly caused by having run the crawler with `save_files_threshold` of 10M, which adds an almost unbounded amount to the work that the DB has to do. There needs to be some work around the behaviour for saving more files, but I'm closing this for now because the problem is caused by having a setting that greatly deviates from the default/recommended settings.

**Closed by mgdigital** 2024-07-04 15:33 UTC
Labels: bug
